### ISSUE TITLE
Link EC Projects (Awards vocabulary) to EuroSciVoc subjects and participating organizations with data from CORDIS

### ISSUE THREAD

**Issue by ptamarit** [inveniosoftware/invenio-vocabularies#382]
```[tasklist]
### Tasks
- [ ] https://github.com/inveniosoftware/invenio-vocabularies/issues/393
```

# CORDIS Data sources

1. As an API (aka Datalab)
    * [CORDIS - Datalab](https://cordis.europa.eu/datalab)
    * API URL: https://cordis.europa.eu/user/api/en
    * Requires an EU login
2. As a dataset
	* [CORDIS - Projects & results](https://cordis.europa.eu/projects)
	* Under the "Download projects as open data" section, follow the [Download all Horizon Europe projects](https://data.europa.eu/data/datasets/cordis-eu-research-projects-under-horizon-europe-2021-2027?locale=en) button
	* [Direct link to download the Horizon Europe Projects in CSV format](https://cordis.europa.eu/data/cordis-HORIZONprojects-csv.zip)
	* [Direct link to download the Horizon Europe Projects in JSON format](https://cordis.europa.eu/data/cordis-HORIZONprojects-json.zip)
	* [Direct link to download the Horizon Europe Projects in individual XML files, which contain the information about the organization in the same file as the project itself](https://cordis.europa.eu/data/cordis-HORIZONprojects-xml.zip)

# Determining CORDIS data modification dates

1. The [web UI](https://data.europa.eu/data/datasets/cordis-eu-research-projects-under-horizon-europe-2021-2027?locale=en) contains a global "Updated" date as well as individual "Updated" dates for each file download.
2. The "Linked data" downloadable from the [web UI](https://data.europa.eu/data/datasets/cordis-eu-research-projects-under-horizon-europe-2021-2027?locale=en) also contain matching "modified" fields, but the download URLs do not seem to be guessable.
3. The individual XML files contain a `contentCreationDate`, `contentUpdateDate`, `sourceUpdateDate`, and `lastUpdateDate` tag for each project file. However, none of them is as recent as the "2024-08-08" date published on the web UI as of this writing (2024-08-12).
4. The CSV and JSON project files only contain `contentUpdateDate`, and it does match with `contentUpdateDate` in the individual XML files.

# Participant Identification Code (PIC) to ROR

1. [paulmillar/PIC-to-ROR](https://github.com/paulmillar/PIC-to-ROR/)
    * The [version hosted on paulmillar.github.io](https://paulmillar.github.io/cordis/pic-to-ror.json) contains 2474 entries
    * Re-running the process generates a file containing 2641 entries.
        * `git clone https://github.com/paulmillar/PIC-to-ROR.git`
        * `cd PIC-to-ROR`
        * Edit `bin/acquire-data`, for the variable `metadata_url` remove the `/` after `records`.
        * `bin/acquire-data`
        * `python -m venv .venv`
        * `source .venv/bin/activate`
        * `pip install gitpython sparqlwrapper geopy`
        * `git tag 0.1.0`
        * `git tag -a 0.1.0 -m "release: 0.1.0"`
        * ```bash
          $ ./process.py data/organization.csv
          Loaded 110212 organisations from ROR data dump
          Loaded 41836 organisations from CORDIS data
          Wikidata has 2629 organisations with PIC and ROR information
          Wikidata has 2913 organisations with EU VAT and ROR information
          MEDIAN DISTANCE: 1.5681415233811342 km
          Skipping 905144443 --> https://ror.org/053194h78: No location information for PIC 905144443 in CORDIS data
          Summary:
              2641 Total mapped
          Mapped organisations written as "pic-to-ror.json".
          ```
    * Re-running the process for Horizon Europe instead of H2020 generates a file containing 1797 entries.
        * Edit `acquire-data`, replace `h2020` by `HORIZON` twice
        * `bin/acquire-data`
        * ```bash
          $ ./process.py data/organization.csv
          Loaded 110212 organisations from ROR data dump
          Loaded 24049 organisations from CORDIS data
          Wikidata has 2629 organisations with PIC and ROR information
          Wikidata has 2913 organisations with EU VAT and ROR information
          MEDIAN DISTANCE: 1.4825546435263037 km
          Skipping 909860874 --> https://ror.org/057g20z61: No location information for PIC 909860874 in CORDIS data
          Skipping 938773179 --> https://ror.org/027ynra39: No location information for PIC 938773179 in CORDIS data
          Skipping 987022046 --> https://ror.org/04jt5e503: No location information for PIC 987022046 in CORDIS data
          Summary:
              1797 Total mapped
          Mapped organisations written as "pic-to-ror.json".
          ```
2. OpenAIRE OpenOrgs
    * Video from 2021: [Demo: OpenOrgs: OpenAIRE's tool for bridging registries of research organisations](https://www.youtube.com/watch?v=wdvAu8cCWws)
    * Blog post from 2023: [OpenOrgs: the OpenAIRE service for bridging registries of research organisations](https://www.openaire.eu/openorgs-the-openaire-service-for-bridging-registries-of-research-organisations)
    * Blog post from 2024: [The Brand-New OpenAIRE OpenOrgs Website is Now Live!](https://www.openaire.eu/the-brand-new-openaire-openorgs-website-is-now-live)
    * Address of the platform (seems to require becoming a curator to get access): [orgs.openaire.eu](https://orgs.openaire.eu/)
3. Some organizations in the [full OpenAIRE Graph Dataset](https://doi.org/10.5281/zenodo.3516917) `organization.tar` file contain both ROR and PIC identifiers

# Open questions

- [x] Should we use the API or the dataset as a data source? -> Let's use the data set as a first step (which is consistent with other HTTP Readers like `RORHTTPReader` and `OpenAIREProjectHTTPReader`).
- [ ] How do we determine the last modification date?
- [x] Should we only process Horizon Europe data or Horizon 2020 and FP7 data? -> Let's start with Horizon Europe.
- [x] Should this belong in `awards` (along with OpenAIRE Project) or in a new vocabulary? -> Let's try to "augment" the existing awards vocabulary, adding organizations and subjects data to existing projects imported from OpenAIRE. We should check what to do if the project exists in CORDIS but not in OpenAIRE (should we skip it or create a project?).

**Comment by ptamarit** [comment]
All linked pull requests are closed, so closing this issue.
